### ISSUE TITLE
Unable to use arrow keys or clicking to go back in chat line

### ISSUE THREAD

**Issue by 6god6win6** [oscarpedrero/ChatLineColorMod#6]

**Comment by oscarpedrero** [comment]
This functionality has been deactivated because the channel label puts it as text in the input text and if it was not deactivated when you opened a chat and added the name of the channel, the text would remain selected. I will also review it to see if I find another way or at least be able to configure the mod to leave the channel colors and remove the channel label so that this option remains active.

**Comment by oscarpedrero** [comment]
@6god6win6 A new version is now available in which you can disable only the channel name to have the functionality of being able to select the text or move with the arrow keys available.
